workflow:
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

default:
  image: node:fermium-alpine

stages:
  - prepare
  - test

install-dependencies:
  stage: prepare
  script:
    - yarn install --frozen-lockfile
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules
      - build

test:
  stage: test
  coverage: "/^Statements\\s*:\\s*([^%]+)/"
  script:
    - yarn lint
    - 'jest --ci --reporters=default --reporters=jest-junit'
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules
    policy: pull
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
